{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2021-26813",
	"modified": "2025-01-13T10:22:30Z",
	"published": "2021-03-03T16:15:00Z",
	"related": [
		"CVE-2021-26813"
	],
	"details": "markdown2 >=1.0.1.18, fixed in 2.4.0, is affected by a regular expression denial of service vulnerability. If an attacker provides a malicious string, it can make markdown2 processing difficult or delayed for an extended period of time.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:20.04:LTS",
				"name": "python-markdown2",
				"purl": "pkg:deb/ubuntu/python-markdown2@2.3.7-2?arch=source&distro=focal"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"2.3.7-2"
			],
			"ecosystem_specific": {
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2021/UBUNTU-CVE-2021-26813.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:22.04:LTS",
				"name": "python-markdown2",
				"purl": "pkg:deb/ubuntu/python-markdown2@2.4.1-1?arch=source&distro=jammy"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"2.3.10-1.1",
				"2.4.1-1"
			],
			"ecosystem_specific": {
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2021/UBUNTU-CVE-2021-26813.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:24.10",
				"name": "python-markdown2",
				"purl": "pkg:deb/ubuntu/python-markdown2@2.4.11-1?arch=source&distro=oracular"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"2.4.11-1"
			],
			"ecosystem_specific": {
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2021/UBUNTU-CVE-2021-26813.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:24.04:LTS",
				"name": "python-markdown2",
				"purl": "pkg:deb/ubuntu/python-markdown2@2.4.11-1?arch=source&distro=noble"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"2.4.1-1",
				"2.4.11-1"
			],
			"ecosystem_specific": {
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2021/UBUNTU-CVE-2021-26813.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2021-26813"
		},
		{
			"type": "REPORT",
			"url": "https://github.com/trentm/python-markdown2/pull/387"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2021-26813"
		}
	]
}
