{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2021-40083",
	"modified": "2025-01-13T10:22:37Z",
	"published": "2021-08-25T01:15:00Z",
	"related": [
		"CVE-2021-40083"
	],
	"details": "Knot Resolver before 5.3.2 is prone to an assertion failure, triggerable by a remote attacker in an edge case (NSEC3 with too many iterations used for a positive wildcard proof).",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:22.04:LTS",
				"name": "knot-resolver",
				"purl": "pkg:deb/ubuntu/knot-resolver@5.4.4-1?arch=source&distro=jammy"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "5.4.4-1"
						}
					]
				}
			],
			"versions": [
				"5.3.1-1",
				"5.4.2-1",
				"5.4.3-1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "knot-resolver",
						"binary_version": "5.4.4-1"
					},
					{
						"binary_name": "knot-resolver-dbgsym",
						"binary_version": "5.4.4-1"
					},
					{
						"binary_name": "knot-resolver-doc",
						"binary_version": "5.4.4-1"
					},
					{
						"binary_name": "knot-resolver-module-http",
						"binary_version": "5.4.4-1"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2021/UBUNTU-CVE-2021-40083.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2021-40083"
		},
		{
			"type": "REPORT",
			"url": "https://gitlab.nic.cz/knot/knot-resolver/-/merge_requests/1169"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2021-40083"
		}
	]
}
