{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2019-12761",
	"modified": "2019-06-06T19:29:00Z",
	"published": "2019-06-06T19:29:00Z",
	"related": [
		"CVE-2019-12761",
		"USN-4700-1"
	],
	"details": "A code injection issue was discovered in PyXDG before 0.26 via crafted Python code in a Category element of a Menu XML document in a .menu file. XDG_CONFIG_DIRS must be set up to trigger xdg.Menu.parse parsing within the directory containing this file. This is due to a lack of sanitization in xdg/Menu.py before an eval call.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:14.04:LTS",
				"name": "pyxdg",
				"purl": "pkg:deb/ubuntu/pyxdg?arch=src?distro=trusty/esm"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0.25-4ubuntu0.14.04.1~esm1"
						}
					]
				}
			],
			"versions": [
				"0.25-3",
				"0.25-4"
			],
			"ecosystem_specific": {
				"availability": "Available with Ubuntu Pro (Infra-only): https://ubuntu.com/pro",
				"binaries": [
					{
						"binary_name": "python-xdg",
						"binary_version": "0.25-4ubuntu0.14.04.1~esm1"
					},
					{
						"binary_name": "python3-xdg",
						"binary_version": "0.25-4ubuntu0.14.04.1~esm1"
					}
				],
				"ubuntu_priority": "low"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2019/UBUNTU-CVE-2019-12761.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:16.04:LTS",
				"name": "pyxdg",
				"purl": "pkg:deb/ubuntu/pyxdg?arch=src?distro=xenial"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0.25-4ubuntu0.16.04.1"
						}
					]
				}
			],
			"versions": [
				"0.25-4"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-xdg",
						"binary_version": "0.25-4ubuntu0.16.04.1"
					},
					{
						"binary_name": "python3-xdg",
						"binary_version": "0.25-4ubuntu0.16.04.1"
					}
				],
				"ubuntu_priority": "low"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2019/UBUNTU-CVE-2019-12761.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:18.04:LTS",
				"name": "pyxdg",
				"purl": "pkg:deb/ubuntu/pyxdg?arch=src?distro=bionic"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0.25-4ubuntu1.1"
						}
					]
				}
			],
			"versions": [
				"0.25-4",
				"0.25-4ubuntu1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-xdg",
						"binary_version": "0.25-4ubuntu1.1"
					},
					{
						"binary_name": "python3-xdg",
						"binary_version": "0.25-4ubuntu1.1"
					}
				],
				"ubuntu_priority": "low"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2019/UBUNTU-CVE-2019-12761.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2019-12761"
		},
		{
			"type": "REPORT",
			"url": "https://snyk.io/vuln/SNYK-PYTHON-PYXDG-174562"
		},
		{
			"type": "REPORT",
			"url": "https://gist.github.com/dhondta/b45cd41f4186110a354dc7272916feba"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/notices/USN-4700-1"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2019-12761"
		}
	]
}
