{
	"schema_version": "1.6.0",
	"id": "USN-3039-1",
	"modified": "2016-07-19T17:59:41.951644Z",
	"published": "2016-07-19T17:59:41.951644Z",
	"related": [
		"CVE-2016-6186",
		"UBUNTU-CVE-2016-6186"
	],
	"summary": "python-django vulnerability",
	"details": "It was discovered that Django incorrectly handled the admin's add/change\nrelated popup. A remote attacker could possibly use this issue to perform a\ncross-site scripting attack.\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:16.04:LTS",
				"name": "python-django",
				"purl": "pkg:deb/ubuntu/python-django@1.8.7-1ubuntu5.1?arch=source&distro=xenial"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.8.7-1ubuntu5.1"
						}
					]
				}
			],
			"versions": [
				"1.7.9-1ubuntu5",
				"1.8.5-2ubuntu1",
				"1.8.7-1ubuntu1",
				"1.8.7-1ubuntu2",
				"1.8.7-1ubuntu3",
				"1.8.7-1ubuntu4",
				"1.8.7-1ubuntu5"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-django",
						"binary_version": "1.8.7-1ubuntu5.1"
					},
					{
						"binary_name": "python-django-common",
						"binary_version": "1.8.7-1ubuntu5.1"
					},
					{
						"binary_name": "python-django-doc",
						"binary_version": "1.8.7-1ubuntu5.1"
					},
					{
						"binary_name": "python3-django",
						"binary_version": "1.8.7-1ubuntu5.1"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-3039-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://ubuntu.com/security/notices/USN-3039-1"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2016-6186"
		}
	]
}
