{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2017-18342",
	"modified": "2025-01-13T10:21:30Z",
	"published": "2018-06-27T12:29:00Z",
	"related": [
		"CVE-2017-18342"
	],
	"details": "In PyYAML before 5.1, the yaml.load() API could execute arbitrary code if used with untrusted data. The load() function has been deprecated in version 5.1 and the 'UnsafeLoader' has been introduced for backward compatibility with the function.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
		},
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:14.04:LTS",
				"name": "pyyaml",
				"purl": "pkg:deb/ubuntu/pyyaml@3.10-4ubuntu0.1?arch=source&distro=esm-infra-legacy/trusty"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"3.10-4build2",
				"3.10-4build3",
				"3.10-4build4",
				"3.10-4ubuntu0.1"
			],
			"ecosystem_specific": {
				"ubuntu_priority": "low"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2017/UBUNTU-CVE-2017-18342.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:16.04:LTS",
				"name": "pyyaml",
				"purl": "pkg:deb/ubuntu/pyyaml@3.11-3build1?arch=source&distro=esm-infra/xenial"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"3.11-2build1",
				"3.11-3",
				"3.11-3build1"
			],
			"ecosystem_specific": {
				"ubuntu_priority": "low"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2017/UBUNTU-CVE-2017-18342.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:18.04:LTS",
				"name": "pyyaml",
				"purl": "pkg:deb/ubuntu/pyyaml@3.12-1build2?arch=source&distro=esm-infra/bionic"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"3.12-1build2"
			],
			"ecosystem_specific": {
				"ubuntu_priority": "low"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2017/UBUNTU-CVE-2017-18342.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:20.04:LTS",
				"name": "pyyaml",
				"purl": "pkg:deb/ubuntu/pyyaml@5.1.2-1?arch=source&distro=focal"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "5.1.2-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-yaml",
						"binary_version": "5.1.2-1"
					},
					{
						"binary_name": "python-yaml-dbg",
						"binary_version": "5.1.2-1"
					},
					{
						"binary_name": "python3-yaml",
						"binary_version": "5.1.2-1"
					},
					{
						"binary_name": "python3-yaml-dbg",
						"binary_version": "5.1.2-1"
					}
				],
				"ubuntu_priority": "low"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2017/UBUNTU-CVE-2017-18342.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2017-18342"
		},
		{
			"type": "REPORT",
			"url": "https://github.com/yaml/pyyaml/pull/74"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2017-18342"
		}
	]
}
