{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2024-5629",
	"modified": "2024-12-18T16:35:38Z",
	"published": "2024-06-05T15:15:00Z",
	"related": [
		"CVE-2024-5629",
		"USN-6904-1"
	],
	"details": "An out-of-bounds read in the 'bson' module of PyMongo 4.6.2 or earlier allows deserialization of malformed BSON provided by a Server to raise an exception which may contain arbitrary application memory.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:14.04:LTS",
				"name": "pymongo",
				"purl": "pkg:deb/ubuntu/pymongo?arch=src?distro=esm-infra-legacy/trusty"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"2.6-1",
				"2.6.2-1",
				"2.6.3-1",
				"2.6.3-1build1"
			],
			"ecosystem_specific": {
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2024/UBUNTU-CVE-2024-5629.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:16.04:LTS",
				"name": "pymongo",
				"purl": "pkg:deb/ubuntu/pymongo?arch=src?distro=esm-infra/xenial"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.2-1ubuntu0.1~esm1"
						}
					]
				}
			],
			"versions": [
				"3.0.3-1",
				"3.2-1",
				"3.2-1build1"
			],
			"ecosystem_specific": {
				"availability": "Available with Ubuntu Pro (Infra-only): https://ubuntu.com/pro",
				"binaries": [
					{
						"binary_name": "python-bson",
						"binary_version": "3.2-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python-bson-ext",
						"binary_version": "3.2-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python-gridfs",
						"binary_version": "3.2-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python-pymongo",
						"binary_version": "3.2-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python-pymongo-doc",
						"binary_version": "3.2-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python-pymongo-ext",
						"binary_version": "3.2-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-bson",
						"binary_version": "3.2-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-bson-ext",
						"binary_version": "3.2-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-gridfs",
						"binary_version": "3.2-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-pymongo",
						"binary_version": "3.2-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-pymongo-ext",
						"binary_version": "3.2-1ubuntu0.1~esm1"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2024/UBUNTU-CVE-2024-5629.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:18.04:LTS",
				"name": "pymongo",
				"purl": "pkg:deb/ubuntu/pymongo?arch=src?distro=esm-infra/bionic"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.1+dfsg1-1ubuntu0.1~esm1"
						}
					]
				}
			],
			"versions": [
				"3.4.0-1build2",
				"3.6.1+dfsg1-1"
			],
			"ecosystem_specific": {
				"availability": "Available with Ubuntu Pro (Infra-only): https://ubuntu.com/pro",
				"binaries": [
					{
						"binary_name": "python-bson",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python-bson-ext",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python-bson-ext-dbgsym",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python-gridfs",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python-pymongo",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python-pymongo-doc",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python-pymongo-ext",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python-pymongo-ext-dbgsym",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-bson",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-bson-ext",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-bson-ext-dbgsym",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-gridfs",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-pymongo",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-pymongo-ext",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-pymongo-ext-dbgsym",
						"binary_version": "3.6.1+dfsg1-1ubuntu0.1~esm1"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2024/UBUNTU-CVE-2024-5629.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:20.04:LTS",
				"name": "pymongo",
				"purl": "pkg:deb/ubuntu/pymongo?arch=src?distro=focal"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.10.1-0ubuntu2.1"
						}
					]
				}
			],
			"versions": [
				"3.7.1-1.1",
				"3.7.1-1.1build1",
				"3.10.1-0ubuntu2"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-pymongo-doc",
						"binary_version": "3.10.1-0ubuntu2.1"
					},
					{
						"binary_name": "python3-bson",
						"binary_version": "3.10.1-0ubuntu2.1"
					},
					{
						"binary_name": "python3-bson-ext",
						"binary_version": "3.10.1-0ubuntu2.1"
					},
					{
						"binary_name": "python3-bson-ext-dbgsym",
						"binary_version": "3.10.1-0ubuntu2.1"
					},
					{
						"binary_name": "python3-gridfs",
						"binary_version": "3.10.1-0ubuntu2.1"
					},
					{
						"binary_name": "python3-pymongo",
						"binary_version": "3.10.1-0ubuntu2.1"
					},
					{
						"binary_name": "python3-pymongo-ext",
						"binary_version": "3.10.1-0ubuntu2.1"
					},
					{
						"binary_name": "python3-pymongo-ext-dbgsym",
						"binary_version": "3.10.1-0ubuntu2.1"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2024/UBUNTU-CVE-2024-5629.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:22.04:LTS",
				"name": "pymongo",
				"purl": "pkg:deb/ubuntu/pymongo?arch=src?distro=jammy"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.11.0-1ubuntu0.22.04.1"
						}
					]
				}
			],
			"versions": [
				"3.11.0-1build2",
				"3.11.0-1build3",
				"3.11.0-1build4"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-pymongo-doc",
						"binary_version": "3.11.0-1ubuntu0.22.04.1"
					},
					{
						"binary_name": "python3-bson",
						"binary_version": "3.11.0-1ubuntu0.22.04.1"
					},
					{
						"binary_name": "python3-bson-ext",
						"binary_version": "3.11.0-1ubuntu0.22.04.1"
					},
					{
						"binary_name": "python3-bson-ext-dbgsym",
						"binary_version": "3.11.0-1ubuntu0.22.04.1"
					},
					{
						"binary_name": "python3-gridfs",
						"binary_version": "3.11.0-1ubuntu0.22.04.1"
					},
					{
						"binary_name": "python3-pymongo",
						"binary_version": "3.11.0-1ubuntu0.22.04.1"
					},
					{
						"binary_name": "python3-pymongo-ext",
						"binary_version": "3.11.0-1ubuntu0.22.04.1"
					},
					{
						"binary_name": "python3-pymongo-ext-dbgsym",
						"binary_version": "3.11.0-1ubuntu0.22.04.1"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2024/UBUNTU-CVE-2024-5629.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:24.04:LTS",
				"name": "pymongo",
				"purl": "pkg:deb/ubuntu/pymongo?arch=src?distro=noble"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.11.0-1ubuntu0.24.04.1"
						}
					]
				}
			],
			"versions": [
				"3.11.0-1build6",
				"3.11.0-1build7",
				"3.11.0-1build8"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-pymongo-doc",
						"binary_version": "3.11.0-1ubuntu0.24.04.1"
					},
					{
						"binary_name": "python3-bson",
						"binary_version": "3.11.0-1ubuntu0.24.04.1"
					},
					{
						"binary_name": "python3-bson-ext",
						"binary_version": "3.11.0-1ubuntu0.24.04.1"
					},
					{
						"binary_name": "python3-bson-ext-dbgsym",
						"binary_version": "3.11.0-1ubuntu0.24.04.1"
					},
					{
						"binary_name": "python3-gridfs",
						"binary_version": "3.11.0-1ubuntu0.24.04.1"
					},
					{
						"binary_name": "python3-pymongo",
						"binary_version": "3.11.0-1ubuntu0.24.04.1"
					},
					{
						"binary_name": "python3-pymongo-ext",
						"binary_version": "3.11.0-1ubuntu0.24.04.1"
					},
					{
						"binary_name": "python3-pymongo-ext-dbgsym",
						"binary_version": "3.11.0-1ubuntu0.24.04.1"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2024/UBUNTU-CVE-2024-5629.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2024-5629"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2024-5629"
		},
		{
			"type": "REPORT",
			"url": "https://jira.mongodb.org/browse/PYTHON-4305"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/notices/USN-6904-1"
		}
	]
}
