{
	"schema_version": "1.6.0",
	"id": "USN-6414-2",
	"modified": "2023-10-04T22:01:08.590378Z",
	"published": "2023-10-04T22:01:08.590378Z",
	"related": [
		"CVE-2023-41164",
		"CVE-2023-43665",
		"UBUNTU-CVE-2023-41164",
		"UBUNTU-CVE-2023-43665"
	],
	"summary": "python-django vulnerabilities",
	"details": "USN-6414-1 and USN-6378-1 fixed CVE-2023-43665 and CVE-2023-41164 in Django,\nrespectively. This update provides the corresponding update for Ubuntu 18.04 LTS.\n\nOriginal advisory details:\n\n Wenchao Li discovered that the Django Truncator function incorrectly\n handled very long HTML input. A remote attacker could possibly use this\n issue to cause Django to consume resources, leading to a denial of service.\n\n It was discovered that Django incorrectly handled certain URIs with a very\n large number of Unicode characters. A remote attacker could possibly use\n this issue to cause Django to consume resources or crash, leading to a\n denial of service.\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:18.04:LTS",
				"name": "python-django",
				"purl": "pkg:deb/ubuntu/python-django?arch=src?distro=esm-infra/bionic"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:1.11.11-1ubuntu1.21+esm2"
						}
					]
				}
			],
			"versions": [
				"1:1.11.4-1ubuntu1",
				"1:1.11.6-1ubuntu1",
				"1:1.11.9-1ubuntu1",
				"1:1.11.11-1ubuntu1",
				"1:1.11.11-1ubuntu1.1",
				"1:1.11.11-1ubuntu1.2",
				"1:1.11.11-1ubuntu1.3",
				"1:1.11.11-1ubuntu1.4",
				"1:1.11.11-1ubuntu1.5",
				"1:1.11.11-1ubuntu1.6",
				"1:1.11.11-1ubuntu1.7",
				"1:1.11.11-1ubuntu1.8",
				"1:1.11.11-1ubuntu1.9",
				"1:1.11.11-1ubuntu1.10",
				"1:1.11.11-1ubuntu1.11",
				"1:1.11.11-1ubuntu1.12",
				"1:1.11.11-1ubuntu1.13",
				"1:1.11.11-1ubuntu1.14",
				"1:1.11.11-1ubuntu1.15",
				"1:1.11.11-1ubuntu1.16",
				"1:1.11.11-1ubuntu1.17",
				"1:1.11.11-1ubuntu1.18",
				"1:1.11.11-1ubuntu1.19",
				"1:1.11.11-1ubuntu1.20",
				"1:1.11.11-1ubuntu1.21",
				"1:1.11.11-1ubuntu1.21+esm1"
			],
			"ecosystem_specific": {
				"availability": "Available with Ubuntu Pro (Infra-only): https://ubuntu.com/pro",
				"binaries": [
					{
						"binary_name": "python-django",
						"binary_version": "1:1.11.11-1ubuntu1.21+esm2"
					},
					{
						"binary_name": "python-django-common",
						"binary_version": "1:1.11.11-1ubuntu1.21+esm2"
					},
					{
						"binary_name": "python-django-doc",
						"binary_version": "1:1.11.11-1ubuntu1.21+esm2"
					},
					{
						"binary_name": "python3-django",
						"binary_version": "1:1.11.11-1ubuntu1.21+esm2"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-6414-2.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://ubuntu.com/security/notices/USN-6414-2"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2023-41164"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2023-43665"
		}
	]
}
