{
	"schema_version": "1.6.0",
	"id": "USN-6226-1",
	"modified": "2023-07-13T03:58:14.052895Z",
	"published": "2023-07-13T03:58:14.052895Z",
	"related": [
		"CVE-2023-25399",
		"CVE-2023-29824",
		"UBUNTU-CVE-2023-25399",
		"UBUNTU-CVE-2023-29824"
	],
	"summary": "scipy vulnerabilities",
	"details": "It was discovered that SciPy did not properly manage memory operations\nduring reference counting. An attacker could possibly use this issue to\ncause a denial of service. (CVE-2023-25399)\n\nA use-after-free was discovered in SciPy when handling reference counts. An\nattacker could possibly use this to cause a denial of service. This issue\nonly affected Ubuntu 20.04 LTS. (CVE-2023-29824)\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:20.04:LTS",
				"name": "scipy",
				"purl": "pkg:deb/ubuntu/scipy@1.3.3-3ubuntu0.1~esm1?arch=source&distro=esm-apps/focal"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.3.3-3ubuntu0.1~esm1"
						}
					]
				}
			],
			"versions": [
				"1.3.3-3",
				"1.3.3-3build1"
			],
			"ecosystem_specific": {
				"availability": "Available with Ubuntu Pro: https://ubuntu.com/pro",
				"binaries": [
					{
						"binary_name": "python-scipy-doc",
						"binary_version": "1.3.3-3ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-scipy",
						"binary_version": "1.3.3-3ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-scipy-dbg",
						"binary_version": "1.3.3-3ubuntu0.1~esm1"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-6226-1.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:22.04:LTS",
				"name": "scipy",
				"purl": "pkg:deb/ubuntu/scipy@1.8.0-1exp2ubuntu1+esm1?arch=source&distro=esm-apps/jammy"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.8.0-1exp2ubuntu1+esm1"
						}
					]
				}
			],
			"versions": [
				"1.6.0-2",
				"1.7.1-1ubuntu1",
				"1.8.0-1exp2ubuntu1"
			],
			"ecosystem_specific": {
				"availability": "Available with Ubuntu Pro: https://ubuntu.com/pro",
				"binaries": [
					{
						"binary_name": "python-scipy-doc",
						"binary_version": "1.8.0-1exp2ubuntu1+esm1"
					},
					{
						"binary_name": "python3-scipy",
						"binary_version": "1.8.0-1exp2ubuntu1+esm1"
					},
					{
						"binary_name": "python3-scipy-dbgsym",
						"binary_version": "1.8.0-1exp2ubuntu1+esm1"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-6226-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://ubuntu.com/security/notices/USN-6226-1"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2023-25399"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2023-29824"
		}
	]
}
