{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2016-10149",
	"modified": "2025-01-13T10:21:17Z",
	"published": "2017-03-24T00:00:00Z",
	"related": [
		"CVE-2016-10149",
		"USN-3402-1"
	],
	"details": "XML External Entity (XXE) vulnerability in PySAML2 4.4.0 and earlier allows remote attackers to read arbitrary files via a crafted SAML XML request or response.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:16.04:LTS",
				"name": "python-pysaml2",
				"purl": "pkg:deb/ubuntu/python-pysaml2@3.0.0-3ubuntu1.16.04.1?arch=source&distro=xenial"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.0.0-3ubuntu1.16.04.1"
						}
					]
				}
			],
			"versions": [
				"2.4.0-0ubuntu2",
				"3.0.0-3ubuntu1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-pysaml2",
						"binary_version": "3.0.0-3ubuntu1.16.04.1"
					},
					{
						"binary_name": "python-pysaml2-doc",
						"binary_version": "3.0.0-3ubuntu1.16.04.1"
					},
					{
						"binary_name": "python3-pysaml2",
						"binary_version": "3.0.0-3ubuntu1.16.04.1"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2016/UBUNTU-CVE-2016-10149.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2016-10149"
		},
		{
			"type": "REPORT",
			"url": "https://github.com/rohe/pysaml2/pull/379"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/notices/USN-3402-1"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2016-10149"
		}
	]
}
