{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2020-9991",
	"modified": "2024-10-15T14:07:56Z",
	"published": "2020-12-08T22:15:00Z",
	"related": [
		"CVE-2020-9991"
	],
	"details": "This issue was addressed with improved checks. This issue is fixed in macOS Big Sur 11.0.1, watchOS 7.0, iOS 14.0 and iPadOS 14.0, iCloud for Windows 7.21, tvOS 14.0. A remote attacker may be able to cause a denial of service.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:16.04:LTS",
				"name": "sqlite",
				"purl": "pkg:deb/ubuntu/sqlite?arch=src?distro=esm-apps/xenial"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"2.8.17-12fakesync1"
			],
			"ecosystem_specific": {
				"ubuntu_priority": "low"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2020/UBUNTU-CVE-2020-9991.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2020-9991"
		},
		{
			"type": "REPORT",
			"url": "https://support.apple.com/en-us/HT211931"
		},
		{
			"type": "REPORT",
			"url": "https://www.rapid7.com/db/vulnerabilities/apple-osx-sqlite-cve-2020-9991/"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2020-9991"
		}
	]
}
