{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2020-35518",
	"modified": "2025-01-13T10:22:20Z",
	"published": "2021-03-26T17:15:00Z",
	"related": [
		"CVE-2020-35518",
		"USN-5231-1"
	],
	"details": "When binding against a DN during authentication, the reply from 389-ds-base will be different whether the DN exists or not. This can be used by an unauthenticated attacker to check the existence of an entry in the LDAP database.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:20.04:LTS",
				"name": "389-ds-base",
				"purl": "pkg:deb/ubuntu/389-ds-base@1.4.3.6-2?arch=source&distro=focal"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"1.4.1.6-4",
				"1.4.1.6-4build1",
				"1.4.2.4-1",
				"1.4.2.4-1build1",
				"1.4.3.2-1",
				"1.4.3.2-1build1",
				"1.4.3.6-2"
			],
			"ecosystem_specific": {
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2020/UBUNTU-CVE-2020-35518.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:Pro:20.04:LTS",
				"name": "389-ds-base",
				"purl": "pkg:deb/ubuntu/389-ds-base@1.4.3.6-2ubuntu0.1~esm1?arch=source&distro=esm-apps/focal"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.4.3.6-2ubuntu0.1~esm1"
						}
					]
				}
			],
			"versions": [
				"1.4.1.6-4",
				"1.4.1.6-4build1",
				"1.4.2.4-1",
				"1.4.2.4-1build1",
				"1.4.3.2-1",
				"1.4.3.2-1build1",
				"1.4.3.6-2"
			],
			"ecosystem_specific": {
				"availability": "Available with Ubuntu Pro: https://ubuntu.com/pro",
				"binaries": [
					{
						"binary_name": "389-ds",
						"binary_version": "1.4.3.6-2ubuntu0.1~esm1"
					},
					{
						"binary_name": "389-ds-base",
						"binary_version": "1.4.3.6-2ubuntu0.1~esm1"
					},
					{
						"binary_name": "389-ds-base-dbgsym",
						"binary_version": "1.4.3.6-2ubuntu0.1~esm1"
					},
					{
						"binary_name": "389-ds-base-dev",
						"binary_version": "1.4.3.6-2ubuntu0.1~esm1"
					},
					{
						"binary_name": "389-ds-base-libs",
						"binary_version": "1.4.3.6-2ubuntu0.1~esm1"
					},
					{
						"binary_name": "389-ds-base-libs-dbgsym",
						"binary_version": "1.4.3.6-2ubuntu0.1~esm1"
					},
					{
						"binary_name": "cockpit-389-ds",
						"binary_version": "1.4.3.6-2ubuntu0.1~esm1"
					},
					{
						"binary_name": "python3-lib389",
						"binary_version": "1.4.3.6-2ubuntu0.1~esm1"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2020/UBUNTU-CVE-2020-35518.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2020-35518"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1905565"
		},
		{
			"type": "REPORT",
			"url": "https://github.com/389ds/389-ds-base/issues/4480"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/notices/USN-5231-1"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2020-35518"
		}
	]
}
