{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2020-27349",
	"modified": "2025-01-13T10:22:18Z",
	"published": "2020-12-08T00:00:00Z",
	"related": [
		"CVE-2020-27349",
		"USN-4664-1"
	],
	"details": "Aptdaemon performed policykit checks after interacting with potentially untrusted files with elevated privileges. This affected versions prior to 1.1.1+bzr982-0ubuntu34.1, 1.1.1+bzr982-0ubuntu32.3, 1.1.1+bzr982-0ubuntu19.5, 1.1.1+bzr982-0ubuntu14.5.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:16.04:LTS",
				"name": "aptdaemon",
				"purl": "pkg:deb/ubuntu/aptdaemon@1.1.1+bzr982-0ubuntu14.5?arch=source&distro=xenial"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.1.1+bzr982-0ubuntu14.5"
						}
					]
				}
			],
			"versions": [
				"1.1.1+bzr982-0ubuntu14",
				"1.1.1+bzr982-0ubuntu14.1",
				"1.1.1+bzr982-0ubuntu14.2",
				"1.1.1+bzr982-0ubuntu14.3",
				"1.1.1+bzr982-0ubuntu14.4"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "aptdaemon",
						"binary_version": "1.1.1+bzr982-0ubuntu14.5"
					},
					{
						"binary_name": "aptdaemon-data",
						"binary_version": "1.1.1+bzr982-0ubuntu14.5"
					},
					{
						"binary_name": "python-aptdaemon",
						"binary_version": "1.1.1+bzr982-0ubuntu14.5"
					},
					{
						"binary_name": "python-aptdaemon.gtk3widgets",
						"binary_version": "1.1.1+bzr982-0ubuntu14.5"
					},
					{
						"binary_name": "python3-aptdaemon",
						"binary_version": "1.1.1+bzr982-0ubuntu14.5"
					},
					{
						"binary_name": "python3-aptdaemon.gtk3widgets",
						"binary_version": "1.1.1+bzr982-0ubuntu14.5"
					},
					{
						"binary_name": "python3-aptdaemon.pkcompat",
						"binary_version": "1.1.1+bzr982-0ubuntu14.5"
					},
					{
						"binary_name": "python3-aptdaemon.test",
						"binary_version": "1.1.1+bzr982-0ubuntu14.5"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2020/UBUNTU-CVE-2020-27349.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:18.04:LTS",
				"name": "aptdaemon",
				"purl": "pkg:deb/ubuntu/aptdaemon@1.1.1+bzr982-0ubuntu19.5?arch=source&distro=bionic"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.1.1+bzr982-0ubuntu19.5"
						}
					]
				}
			],
			"versions": [
				"1.1.1+bzr982-0ubuntu17",
				"1.1.1+bzr982-0ubuntu19",
				"1.1.1+bzr982-0ubuntu19.1",
				"1.1.1+bzr982-0ubuntu19.2",
				"1.1.1+bzr982-0ubuntu19.3",
				"1.1.1+bzr982-0ubuntu19.4"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "aptdaemon",
						"binary_version": "1.1.1+bzr982-0ubuntu19.5"
					},
					{
						"binary_name": "aptdaemon-data",
						"binary_version": "1.1.1+bzr982-0ubuntu19.5"
					},
					{
						"binary_name": "python-aptdaemon",
						"binary_version": "1.1.1+bzr982-0ubuntu19.5"
					},
					{
						"binary_name": "python-aptdaemon.gtk3widgets",
						"binary_version": "1.1.1+bzr982-0ubuntu19.5"
					},
					{
						"binary_name": "python3-aptdaemon",
						"binary_version": "1.1.1+bzr982-0ubuntu19.5"
					},
					{
						"binary_name": "python3-aptdaemon.gtk3widgets",
						"binary_version": "1.1.1+bzr982-0ubuntu19.5"
					},
					{
						"binary_name": "python3-aptdaemon.test",
						"binary_version": "1.1.1+bzr982-0ubuntu19.5"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2020/UBUNTU-CVE-2020-27349.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:20.04:LTS",
				"name": "aptdaemon",
				"purl": "pkg:deb/ubuntu/aptdaemon@1.1.1+bzr982-0ubuntu32.3?arch=source&distro=focal"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.1.1+bzr982-0ubuntu32.3"
						}
					]
				}
			],
			"versions": [
				"1.1.1+bzr982-0ubuntu28",
				"1.1.1+bzr982-0ubuntu30",
				"1.1.1+bzr982-0ubuntu31",
				"1.1.1+bzr982-0ubuntu32",
				"1.1.1+bzr982-0ubuntu32.1",
				"1.1.1+bzr982-0ubuntu32.2"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "aptdaemon",
						"binary_version": "1.1.1+bzr982-0ubuntu32.3"
					},
					{
						"binary_name": "aptdaemon-data",
						"binary_version": "1.1.1+bzr982-0ubuntu32.3"
					},
					{
						"binary_name": "python3-aptdaemon",
						"binary_version": "1.1.1+bzr982-0ubuntu32.3"
					},
					{
						"binary_name": "python3-aptdaemon.gtk3widgets",
						"binary_version": "1.1.1+bzr982-0ubuntu32.3"
					},
					{
						"binary_name": "python3-aptdaemon.test",
						"binary_version": "1.1.1+bzr982-0ubuntu32.3"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2020/UBUNTU-CVE-2020-27349.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2020-27349"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/notices/USN-4664-1"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2020-27349"
		}
	]
}
